
# History

Create a history of all found reviews in the root directory, then verify it exists.
    create found history
    storage entry ./files/published/tracks/__test-tracksHistory.json exists

# Reviews pages

(Re-)create a page that finds all existing reviews and displays them, then verify it exists.
    create reviews pages
    storage entry ./files/published/dashboard.html exists
    storage entry ./files/published/reviews.html exists

# Browser access

Backgrounds: service

Start up a server so we can verify everything from a browser.
    index files at /tracks from published/tracks
    index files at / from published

First check to see the reviews are being indexed.
    go to the tracks webpage
    see tracks history

Access the reviews.
    go to the dashboard webpage
    See "Reviews"

It contains an indexes of found reviews. Select one.
#    See "Feature Result Index"
    See "local a11y"
    click "local a11y"

Now on an individual review, with a timeline and video.
    see step-current
    see video

# Failure report

This report was generated by a11y-fail.
#    extract HTML report from failures.json to files/publish/failures.html
#    storage entry failures.html exists
